---
Name: auc
---
Injector:
  AUCCSVParser:
    class: CSVParser
  AUCProcess:
    class: Symfony\Component\Process\Process
  AUCHTTPClient:
    class: GuzzleHttp\Client
  AUCMetricTask:
    constructor:
      0: %$OpenStack\AUC\OfficialUserGroupOrganizerService
      1: %$OpenStack\AUC\ActiveUserCommitteeWorkingGroupsService
      2: %$OpenStack\AUC\TrackChairService
      3: %$OpenStack\AUC\ActiveModeratorService
      4: %$OpenStack\AUC\SuperuserService
      5: %$OpenStack\AUC\ActiveCommitterService

Member:
  extensions:
    - AUCMetricMember
AUCActiveCommitterService:
  user: openstackdev
  keyfile: '/var/www/.ssh/id_rsa'
AUCMetric:
  expiry: '+6 months'