---
Name: summit_module
After: 'framework/*','cms/*', 'openstack/*'
---
Member:
  extensions:
    - PresentationMemberExtension
    - MemberTokenProvider
    - AttendeeMember
EditProfilePage_Controller:
  extensions:
    - EditProfilePageSummitAttendeeExtension
MemberTokenProvider:
  token_expire: 500000
PresentationCategory:
  extensions:
    - JSONable
    - SummitEntity
PresentationSpeaker:
  extensions:
    - JSONable
    - SummitEntity
    - SummitSpeakerOpenGraphObjectExtension
PresentationTopic:
  extensions:
    - JSONable
    - SummitEntity
SummitPresentationComment:
  extensions:
    - JSONable
Summit:
  extensions:
    - SummitAdminUI
    - JSONable
    - SummitEntity
  random_voting_list_count: 100
SummitTrackChair:
  extensions:
    - JSONable
    - SummitEntity
SummitCategoryChange:
  extensions:
    - JSONable    
Presentation:
  extensions:
    - Sluggable
    - JSONable
    - SummitEntity
    - SummitEventOpenGraphObjectExtension
  status_options:
    - Received
    - In community voting
    - Being reviewed by track chairs
    - accepted
    - not accepted
    - accepted as an alternate
BootstrapMemberLoginForm:
  extensions:
    - BootstrapLoginFormExtension
SummitAttendee:
  extensions:
    - SummitEntity
SummitEvent:
  extensions:
    - SummitEntity
    - SummitEventOpenGraphObjectExtension
SummitEventFeedback:
  extensions:
    - SummitEntity
SummitEventType:
  extensions:
    - SummitEntity
PresentationMaterial:
  extensions:
    - SummitEntity
SummitAbstractLocation:
  extensions:
    - SummitEntity
    - SummitLocationOpenGraphObjectExtension
SummitTicketType:
  extensions:
    - SummitEntity
PresentationCategoryGroup:
  extensions:
    - SummitEntity
SummitLocationMap:
  extensions:
    - SummitEntity
SummitLocationImage:
  extensions:
    - SummitEntity
SummitVenueFloor:
  extensions:
    - SummitEntity
Injector:
    RSVPTextBoxUIBuilder:
      class: RSVPTextBoxQuestionTemplateUIBuilder
    RSVPMemberEmailUIBuilder:
      class: RSVPTextBoxQuestionTemplateUIBuilder
    RSVPMemberFirstNameUIBuilder:
      class: RSVPTextBoxQuestionTemplateUIBuilder
    RSVPMemberLastNameUIBuilder:
      class: RSVPTextBoxQuestionTemplateUIBuilder
    RSVPTextAreaUIBuilder:
        class: RSVPTextAreaQuestionTemplateUIBuilder
    RSVPCheckBoxUIBuilder:
        class: RSVPCheckBoxQuestionTemplateUIBuilder
    RSVPCheckBoxListUIBuilder:
        class: RSVPCheckBoxListQuestionTemplateUIBuilder
    RSVPRadioButtonListUIBuilder:
        class: RSVPRadioButtonListQuestionTemplateUIBuilder
    RSVPComboBoxUIBuilder:
        class: RSVPDropDownQuestionTemplateUIBuilder
    RSVPLiteralUIBuilder:
      class: RSVPLiteralQuestionTemplateUIBuilder
