---
Name: summit_module
After: 'framework/*','cms/*', 'openstack/*'
---
Member:
  extensions:
    - PresentationMemberExtension
    - MemberTokenProvider
    - AttendeeMember
Director:
  rules:
    'submit-slides': 'PresentationSlideSubmissionController'
EditProfilePage_Controller:
  extensions:
    - EditProfilePageSummitAttendeeExtension
MemberTokenProvider:
  token_expire: 500000
PresentationCategory:
  extensions:
    - JSONable
    - SummitEntity
PresentationSpeaker:
  extensions:
    - JSONable
    - SummitEntity
PresentationTopic:
  extensions:
    - JSONable
    - SummitEntity
SummitPresentationComment:
  extensions:
    - JSONable
Summit:
  extensions:
    - JSONable
    - SummitEntity
  random_voting_list_count: 100
SummitTrackChair:
  extensions:
    - JSONable
    - SummitEntity
SummitCategoryChange:
  extensions:
    - JSONable    
Presentation:
  extensions:
    - Sluggable
    - JSONable
    - SummitEntity
  status_options:
    - Received
    - In community voting
    - Being reviewed by track chairs
    - accepted
    - not accepted
    - accepted as an alternate
BootstrapMemberLoginForm:
  extensions:
    - BootstrapLoginFormExtension
SummitAttendee:
  extensions:
    - SummitEntity
SummitEvent:
  extensions:
    - SummitEntity
SummitEventFeedback:
  extensions:
    - SummitEntity
SummitEventType:
  extensions:
    - SummitEntity
PresentationMaterial:
  extensions:
    - SummitEntity
SummitAbstractLocation:
  extensions:
    - SummitEntity
SummitType:
  extensions:
    - SummitEntity
SummitTicketType:
  extensions:
    - SummitEntity
PresentationCategoryGroup:
  extensions:
    - SummitEntity
SummitLocationMap:
  extensions:
    - SummitEntity
SummitLocationImage:
  extensions:
    - SummitEntity