---
Name: surveybuilderapi
---
Injector:
  SurveyRepository:
    class: SapphireSurveyRepository
  TemplateRepository:
    class: SapphireSurveyTemplateRepository
  FoundationMemberRepository:
    class: SapphireFoundationMemberRepository
  SurveyBuilder:
    class: SurveyBuilder
  SurveyManager:
    constructor:
      0: '%$SurveyRepository'
      1: '%$TemplateRepository'
      2: '%$FoundationMemberRepository'
      3: '%$SurveyBuilder'
      4: '%$TransactionManager'

Survey_Controller:
  dependencies:
    SurveyManager: '%$SurveyManager'
    SurveyRepository: '%$SurveyRepository'
---
Name: surveybuilderui
---
Injector:
  TextBoxUIBuilder:
    class: SurveyTextBoxQuestionTemplateUIBuilder
  MemberEmailUIBuilder:
    class: SurveyTextBoxQuestionTemplateUIBuilder
  MemberFirstNameUIBuilder:
    class: SurveyTextBoxQuestionTemplateUIBuilder
  MemberLastNameUIBuilder:
    class: SurveyTextBoxQuestionTemplateUIBuilder
  TextAreaUIBuilder:
      class: SurveyTextAreaQuestionTemplateUIBuilder
  CheckBoxUIBuilder:
      class: SurveyCheckBoxQuestionTemplateUIBuilder
  CheckBoxListUIBuilder:
      class: SurveyCheckBoxListQuestionTemplateUIBuilder
  ComboBoxUIBuilder:
      class: SurveyDropDownQuestionTemplateUIBuilder
  RankingUIBuilder:
        class: SurveyRankingQuestionTemplateUIBuilder